---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/drone/drone-ignore-config

steps:
- name: test
  image: golang:1.11
  commands:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
  - go vet ./...
  - go test ./...
  when:
    event:
    - push

- name: publish
  image: plugins/docker
  settings:
    auto_tag: true
    repo: fbcbarbosa/drone-config
    password:
      from_secret: dockerhub_password
    username: fbcbarbosa
  when:
    branch:
    - master